# Generated by Django 2.0.13 on 2019-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactiontoken',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
    ]
