# Generated by Django 2.0.13 on 2019-06-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_actions', '0003_active_to_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountactiontoken',
            name='active',
        ),
    ]
